### ISSUE TITLE
it's_working

### ISSUE THREAD

**Issue by simpleman3** [simpleman3/output_data#3]
https://github.com/simpleman3/output_data/blob/02a660b1d1764294cf4774397fc0e3e4df38ba21/db2.php#L26

**Comment by ReeNekt** [comment]
Something help

**Comment by simpleman3** [comment]
не работает

**Comment by simpleman3** [comment]
Делал по твоему примеру и не работает с выводом инфы в блоки div

**Comment by ReeNekt** [comment]
можно так же оставлять несколько строк в issue
https://github.com/simpleman3/output_data/blob/02a660b1d1764294cf4774397fc0e3e4df38ba21/db2.php#L26-L30
как именно скину в вк

**Comment by ReeNekt** [comment]
добавь меня в участники на этом проекте
![image](https://user-images.githubusercontent.com/37070967/47663495-38e31a00-dbae-11e8-95f0-17fe7c07c255.png)
в своем репозитории выбираешь настройки, потом collaborators и напиши мой ник - ReeNekt и выбери меня

**Comment by ReeNekt** [comment]
поправил твои изменения тут https://github.com/simpleman3/output_data/pull/4/commits/512a6daa5d4394332ad6cc3d0bba93c0c7aa3e79
можешь закрывать этот issue

**Comment by ReeNekt** [comment]
сам закрою issue
